const resList = [
	{
		info: {
			id: "180059",
			name: "Zam Zam Food Corner",
			cloudinaryImageId: "ndbt86a2rbv063uzsox7",
			locality: "SP NAGAR",
			areaName: "Moula Ali",
			costForTwo: "₹350 for two",
			cuisines: ["Biryani", "Arabian", "Chinese"],
			avgRating: 4,
			parentId: "229543",
			avgRatingString: "4.0",
			totalRatingsString: "1K+",
			sla: {
				deliveryTime: 25,
				lastMileTravel: 2.5,
				serviceability: "SERVICEABLE",
				slaString: "25 mins",
				lastMileTravelString: "2.5 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-01-19 06:00:00",
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: "10% OFF",
				subHeader: "UPTO ₹40",
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-76314dcd-a906-417e-ace2-d3a4395b6510",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/zam-zam-food-corner-sp-nagar-moula-ali-hyderabad-180059",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "713034",
			name: "Shrimmers",
			cloudinaryImageId: "cedfe674d5e12cd64ea8a75b482bc7ce",
			locality: "Chilakalguda",
			areaName: "Padmarao nagar",
			costForTwo: "₹200 for two",
			cuisines: ["Burgers", "Fast Food", "Snacks"],
			avgRating: 4.2,
			parentId: "425877",
			avgRatingString: "4.2",
			totalRatingsString: "1K+",
			sla: {
				deliveryTime: 55,
				lastMileTravel: 10.8,
				serviceability: "SERVICEABLE",
				slaString: "55 mins",
				lastMileTravelString: "10.8 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-01-19 06:00:00",
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: "₹75 OFF",
				subHeader: "ABOVE ₹299",
				discountTag: "FLAT DEAL",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-76314dcd-a906-417e-ace2-d3a4395b6510",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/shrimmers-chilakalguda-padmarao-nagar-hyderabad-713034",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "699243",
			name: "Pizza wings",
			cloudinaryImageId: "b926524f742e1249e0d48730bd3a0bbd",
			locality: "Meharababa Colony",
			areaName: "Yapral Kowkoor",
			costForTwo: "₹500 for two",
			cuisines: ["Fast Food", "Beverages"],
			avgRating: 3.7,
			parentId: "159048",
			avgRatingString: "3.7",
			totalRatingsString: "7",
			sla: {
				deliveryTime: 50,
				lastMileTravel: 4.8,
				serviceability: "SERVICEABLE",
				slaString: "50 mins",
				lastMileTravelString: "4.8 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-01-19 10:10:00",
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: "25% OFF",
				subHeader: "UPTO ₹65",
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-76314dcd-a906-417e-ace2-d3a4395b6510",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/pizza-wings-meharababa-colony-yapral-kowkoor-hyderabad-699243",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "624063",
			name: "Pizza Land",
			cloudinaryImageId: "9eeb007f44af12c36c00bc6bf6e9aa0f",
			locality: "Deen Dayal Nagar",
			areaName: "Yapral Kowkoor",
			costForTwo: "₹250 for two",
			cuisines: ["Pizzas"],
			avgRating: 2.7,
			parentId: "18091",
			avgRatingString: "2.7",
			totalRatingsString: "20+",
			sla: {
				deliveryTime: 39,
				lastMileTravel: 4.9,
				serviceability: "SERVICEABLE",
				slaString: "39 mins",
				lastMileTravelString: "4.9 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-01-19 08:00:00",
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: "25% OFF",
				subHeader: "ABOVE ₹1900",
				discountTag: "FLAT DEAL",
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-76314dcd-a906-417e-ace2-d3a4395b6510",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/pizza-land-deen-dayal-nagar-yapral-kowkoor-hyderabad-624063",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "713033",
			name: "Peppanizze",
			cloudinaryImageId: "d1f427e88dde5cc6fb1a6eae2f56a700",
			locality: "Chilakalguda",
			areaName: "Padmarao nagar",
			costForTwo: "₹200 for two",
			cuisines: ["Pizzas", "Snacks", "Beverages"],
			avgRating: 3.9,
			parentId: "425704",
			avgRatingString: "3.9",
			totalRatingsString: "100+",
			sla: {
				deliveryTime: 59,
				lastMileTravel: 10.8,
				serviceability: "SERVICEABLE",
				slaString: "59 mins",
				lastMileTravelString: "10.8 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-01-19 06:00:00",
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: "₹75 OFF",
				subHeader: "ABOVE ₹299",
				discountTag: "FLAT DEAL",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-76314dcd-a906-417e-ace2-d3a4395b6510",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/peppanizze-chilakalguda-padmarao-nagar-hyderabad-713033",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "727913",
			name: "THE SWALLOW CAFE",
			cloudinaryImageId: "60d8a8a6cf679cd34b56531e701f312c",
			locality: "Neredmet",
			areaName: "Vinayak Nagar",
			costForTwo: "₹200 for two",
			cuisines: ["Cafe", "Snacks", "Italian", "Burgers", "Fast Food"],
			avgRating: 4.2,
			parentId: "432803",
			avgRatingString: "4.2",
			totalRatingsString: "20+",
			sla: {
				deliveryTime: 48,
				lastMileTravel: 4.9,
				serviceability: "SERVICEABLE",
				slaString: "48 mins",
				lastMileTravelString: "4.9 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-01-19 23:59:00",
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: "₹75 OFF",
				subHeader: "ABOVE ₹499",
				discountTag: "FLAT DEAL",
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-76314dcd-a906-417e-ace2-d3a4395b6510",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/the-swallow-cafe-neredmet-vinayak-nagar-hyderabad-727913",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "767135",
			name: "Gokul Tiffins",
			cloudinaryImageId: "f1bc9ddf53de574cdc35ab2f717df234",
			locality: "Khapra",
			areaName: "AS RAO NAGAR",
			costForTwo: "₹197 for two",
			cuisines: ["South Indian", "Snacks"],
			avgRating: 3.8,
			veg: true,
			parentId: "88209",
			avgRatingString: "3.8",
			totalRatingsString: "20+",
			sla: {
				deliveryTime: 48,
				lastMileTravel: 3.6,
				serviceability: "SERVICEABLE",
				slaString: "48 mins",
				lastMileTravelString: "3.6 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-01-19 11:00:00",
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			isNewlyOnboarded: true,
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-76314dcd-a906-417e-ace2-d3a4395b6510",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/gokul-tiffins-khapra-as-rao-nagar-hyderabad-767135",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "665594",
			name: "Bhamma Kitchen",
			cloudinaryImageId: "c3bc32ad3ed9515bb0bf77c419d5a429",
			locality: "BJR Nagar",
			areaName: "Tarnaka, Nacharam & Malkajigiri",
			costForTwo: "₹250 for two",
			cuisines: ["South Indian", "Chinese", "Burgers", "Snacks", "Beverages"],
			avgRating: 3.8,
			parentId: "399014",
			avgRatingString: "3.8",
			totalRatingsString: "100+",
			sla: {
				deliveryTime: 61,
				lastMileTravel: 7.3,
				serviceability: "SERVICEABLE",
				slaString: "61 mins",
				lastMileTravelString: "7.3 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-01-19 05:30:00",
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: "15% OFF",
				subHeader: "ABOVE ₹1200",
				discountTag: "FLAT DEAL",
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-76314dcd-a906-417e-ace2-d3a4395b6510",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/bhamma-kitchen-bjr-nagar-tarnaka-nacharam-and-malkajigiri-hyderabad-665594",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
	{
		info: {
			id: "678697",
			name: "Cloud Bites",
			cloudinaryImageId: "fa7acbdecdf4377538503551a82eb738",
			locality: "Laxmi Starch Colony",
			areaName: "Tarnaka",
			costForTwo: "₹200 for two",
			cuisines: ["Home Food", "Italian"],
			avgRating: 4.1,
			parentId: "461290",
			avgRatingString: "4.1",
			totalRatingsString: "100+",
			sla: {
				deliveryTime: 68,
				lastMileTravel: 8.8,
				serviceability: "SERVICEABLE",
				slaString: "68 mins",
				lastMileTravelString: "8.8 km",
				iconType: "ICON_TYPE_EMPTY",
			},
			availability: {
				nextCloseTime: "2024-01-19 06:00:00",
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: "F",
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			loyaltyDiscoverPresentationInfo: {
				logoCtx: {
					text: "BENEFITS",
					logo: "v1634558776/swiggy_one/OneLogo_3x.png",
				},
				freedelMessage: "FREE DELIVERY",
			},
			orderabilityCommunication: {
				title: {},
				subTitle: {},
				message: {},
				customIcon: {},
			},
			differentiatedUi: {
				displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
				differentiatedUiMediaDetails: {
					mediaType: "ADS_MEDIA_ENUM_IMAGE",
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
			restaurantOfferPresentationInfo: {},
		},
		analytics: {
			context: "seo-data-76314dcd-a906-417e-ace2-d3a4395b6510",
		},
		cta: {
			link: "https://www.swiggy.com/restaurants/cloud-bites-laxmi-starch-colony-tarnaka-hyderabad-678697",
			text: "RESTAURANT_MENU",
			type: "WEBLINK",
		},
		widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
	},
];

export default resList;
